serverPort: 8899

deployments:
  - name: Kvark
    repository: TIHLDE/Kvark
    ref: refs/heads/production
    # deploymentScript: deployment-scripts/kvark.bash
    deploymentScript: deployment-scripts/dummy.bash

  - name: API
    repository: TIHLDE/API
    ref: refs/heads/production
    deploymentScript: deployment-scripts/API.bash
