serverPort: 8899

deployments:
  - name: Web frontend Kvark
    repository: tihlde/Kvark
    ref: refs/heads/production
    deploymentScript: deployment-scripts/kvark.bash

  - name: Web API
    repository: tihlde/API
    ref: refs/heads/production
    deploymentScript: deployment-scripts/API.bash
