serverPort: 8899
tempDir: /var/temp/webhook-deploy

deployments:
  - name: Sample deployment specification
    repository: mchyll/webhook-deploy
    ref: refs/heads/production
    deploymentScript: deployment-scripts/example.bash
